services:
  postgresql:
    image: postgres:13-alpine
    restart: always
    container_name: postgres.da2
    command: postgres -c max_connections=200
    environment:
      ENV: ${ENV:-develop}
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  api:
    build:
      dockerfile: ./docker/api/Dockerfile
    container_name: api.da2
    environment:
      ENV: ${ENV:-develop}
      PORT: 8080
      # POSTGRES_HOST: postgres.da2
      # AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      # AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # AWS_REGION: ${AWS_REGION}
    volumes:
      - ./signaling-server:/usr/src/app
    ports:
      - 8080:8080

  redis:
    image: redis:latest
    restart: always
    container_name: redis.da2
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data

  